name: Python SVM CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-svm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'   # or your required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy scikit-learn  # add others if needed

    - name: Run SVM script
      run: python svm.py
